services:

  batiknesia:
    container_name: BATIKNESIA
    build: .
    volumes:
      - ./UAS-BATIKNESIA:/var/www/html
    ports:
      - 5000:80
  
  mysql_database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_tokobatik
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 5002:80
    environment:
      - PMA_ARBITRARY=1